apiVersion: v1
kind: Pod
metadata:
  name: multi-container-pod
  labels:
    project: roboshop
    purpose: demo
spec:                       # <-- moved out of metadata
  containers:
    - name: nginx-container
      image: nginx:latest
      ports:
        - containerPort: 80
    - name: almalinux-container
      image: almalinux:9
