apiVersion: v1
kind: Pod
metadata:
  name: labels
  labels:
    project: roboshop
    purpose: demo
    environment: dev
spec:
  containers:
    - name: nginx-container
      image: nginx:latest
      ports:
        - containerPort: 80
